package no.ntnu.idata2900.project.backend.sources;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import no.ntnu.idata2900.project.backend.generators.DataPointGenerator;
import no.ntnu.idata2900.project.backend.models.Trip;
import no.ntnu.idata2900.project.backend.models.datapoints.DataPoint;
import no.ntnu.idata2900.project.backend.services.ModelService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * The FakeDataSource class simulates a data source to produce boat-related data at intervals.
 * It implements the DataSource interface and sends generated ship data to a DataListener.
 * This class is primarily designed for testing or simulation purposes where no actual data source
 * exists.
 *
 * @author Group 14
 * @version v0.2.2 (2025.05.13)
 */
@Component
public class FakeDataSource implements DataSource {

  private ScheduledExecutorService scheduler;
  private DataListener listener;
  private int num;
  private List<DataPoint> clients; // Contains the last data point of each client

  private final DataPointGenerator generator;
  private final ModelService modelService;

  private final Logger logger = LoggerFactory.getLogger(FakeDataSource.class);

  /**
   * Constructor for the FakeDataSource class. The constructor is annotated with
   * <code>@Autowired</code>, meaning that Spring Boot will automatically inject the specified
   * instanes to instances of the class.
   *
   * @param generator    The specified data point generator
   * @param modelService The specified model service
   */
  @Autowired
  public FakeDataSource(DataPointGenerator generator, ModelService modelService) {
    this.generator = generator;
    this.modelService = modelService;
    this.num = 0;
    this.clients = new ArrayList<>();
  }

  /**
   * Add a client to the specified {@link Trip trip}.
   *
   * @param trip The specified trip
   */
  public void addClient(Trip trip) {
    this.logger.info("Adding client with ID: {}", trip.getId());
    this.clients.add(this.generator.generate(null, trip));
    this.logger.info("Printing client datapoints");
    this.clients.forEach(dp -> this.logger.info("Client data point: {}", dp));
  }

  /**
   * Remove a client from the specified {@link Trip trip}.
   *
   * @param trip The specified trip
   */
  public void removeClient(Trip trip) {
    this.logger.info("Removing client with ID: {}", trip.getId());
    this.clients.removeIf(dp -> dp.getTrip().getId().equals(trip.getId()));
  }

  /**
   * Restore the specified clients.
   *
   * @param clients The specified clients
   */
  public void restoreClients(List<DataPoint> clients) {
    this.logger.info("Restoring clients");
    this.clients = clients;
  }

  @Override
  public void start() {
    this.logger.debug("Starting FakeDataSource...");
    // Make sure any existing scheduler is shut down
    if (this.scheduler != null && !this.scheduler.isShutdown()) {
      this.scheduler.shutdownNow();
    }

    this.scheduler = Executors.newSingleThreadScheduledExecutor();

    this.scheduler.scheduleAtFixedRate(() -> {
      this.logger.debug("start of scheduled task");
      if (this.listener != null) {
        List<DataPoint> updatedClients = new ArrayList<>();
        for (DataPoint dp : this.clients) {
          this.logger.info("processing a client datapoint");
          DataPoint updatedDp = this.generator.generate(dp, dp.getTrip());
          DataPoint predictedDp = this.modelService.fetchTargetValues(updatedDp);
          updatedClients.add(predictedDp);
          this.logger.info("Client data point after update: {}", predictedDp);
          this.listener.onDataReceived(predictedDp);
        }
        this.clients = updatedClients;
      }
      this.num = (this.num + 1);
    }, 0, 15, TimeUnit.SECONDS);

    this.logger.info("[FAKE DATASOURCE] Started");
  }

  /**
   * Sets the data listener for this data source.
   * This listener will be notified whenever new data, such as a {@link DataPoint},
   * is generated by the fake data source. The assigned listener must implement
   * the {@link DataListener} interface, with its {@code onDataReceived} method
   * being invoked upon data updates.
   *
   * @param listener The {@link DataListener} instance to receive updated ship data.
   */
  @Override
  public void setDataListener(DataListener listener) {
    this.listener = listener;
    this.logger.info("[FAKE DATASOURCE] Sending data");
  }
}
